// <auto-generated />
using System;
using AdatechTask.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdatechTask.Data.Migrations
{
    [DbContext(typeof(AdatechTaskContext))]
    [Migration("20230924103011_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdatechTask.Entities.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ahmet Yılmaz",
                            Category = "Programlama",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9656),
                            ISBN = "978-1234567890",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9657),
                            PageCount = 400,
                            PublicationDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "XYZ Yayınevi",
                            Title = "C# Programlama"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mehmet Demir",
                            Category = "Programlama",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9666),
                            ISBN = "978-0987654321",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9667),
                            PageCount = 350,
                            PublicationDate = new DateTime(2021, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "ABC Yayınevi",
                            Title = "Python Programlama"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ayşe Kaya",
                            Category = "Programlama",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9673),
                            ISBN = "978-9876543210",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9674),
                            PageCount = 500,
                            PublicationDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "DEF Yayınevi",
                            Title = "Java Programlama"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ali Can",
                            Category = "Veri Bilimi",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9680),
                            ISBN = "978-1357924680",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9681),
                            PageCount = 300,
                            PublicationDate = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "GHI Yayınevi",
                            Title = "Veri Bilimi Temelleri"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Merve Eren",
                            Category = "Web Geliştirme",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9687),
                            ISBN = "978-5432109876",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9688),
                            PageCount = 250,
                            PublicationDate = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "JKL Yayınevi",
                            Title = "Web Geliştirme Temelleri"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Canan Yıldız",
                            Category = "Mobil Uygulama",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9693),
                            ISBN = "978-2468135790",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9694),
                            PageCount = 320,
                            PublicationDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "MNO Yayınevi",
                            Title = "Mobil Uygulama Geliştirme"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Selim Kaya",
                            Category = "Yapay Zeka",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9700),
                            ISBN = "978-7654321098",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9701),
                            PageCount = 280,
                            PublicationDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "STU Yayınevi",
                            Title = "Yapay Zeka ve Makine Öğrenimi"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Ayşe Yılmaz",
                            Category = "Edebiyat",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9707),
                            ISBN = "978-8765432109",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9707),
                            PageCount = 320,
                            PublicationDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "UVW Yayınevi",
                            Title = "Edebiyatın Derinlikleri"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Emre Can",
                            Category = "Tarih",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9713),
                            ISBN = "978-9876543210",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9714),
                            PageCount = 350,
                            PublicationDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "XYZ Yayınevi",
                            Title = "Tarih Sayfalarında Gezi"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Emirhan Aydın",
                            Category = "Tarih",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9720),
                            ISBN = "978-3692581470",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2023, 9, 24, 13, 30, 11, 163, DateTimeKind.Local).AddTicks(9720),
                            PageCount = 400,
                            PublicationDate = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "PQR Yayınevi",
                            Title = "Bilim ve Teknoloji Tarihi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
